services:
  gater:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - consul
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_PROVIDER=consul
      - CONSUL_ADDRESS=consul:8500
    restart: always

  consul:
    image: hashicorp/consul:latest
    restart: always
    ports:
      - "8500:8500"
    command: agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data
