services:
  user:
    image: hashicorp/http-echo
    command: -text='{"service":"user", "status":"ok"}' -listen=:8081
    ports:
      - "8081:8081"

  post:
    image: hashicorp/http-echo
    command: -text='{"service":"post", "status":"ok"}' -listen=:8082
    ports:
      - "8082:8082"

  gater:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - user
      - post
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
